### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by rom1504**
Merge this only after doing this:

when you create a "Release x.y.z" it will release

you need to add a secret called PYPI_PASSWORD in the github repo and put inside a token you create at https://pypi.org/manage/account/token/

https://github.com/FreddeFrallan/Multilingual-CLIP/settings/secrets/actions/new

Choose the option "Squash and merge" on github when merging to create a single commit

### CODE REVIEW

**Comment by FreddeFrallan** [comment]
I have added the secret.

**Comment by rom1504** [comment]
```
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
         The user 'FreddeFrallan' isn't allowed to upload to project 'mclip'.   
         See https://pypi.org/help/#project-name for more information.        
 ```
 
the token need to be for the whole account to be able to create the project

then if you want you can change it to a project specific token

**Comment by rom1504** [comment]
https://pypi.org/simple/mclip/ actually it seems that mclip already exists
Let's go with m-clip

**Comment by rom1504** [comment]
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         The name 'm-clip' is too similar to an existing project. See

**Pull request merged**
